# this docker-compose file is used for running tests in CI/CD pipelines or local testing environments

name: nuvix-test
services:
  postgres:
    image: nuvix/postgres
    container_name: nuvix-test-postgres
    env_file:
      - .env.test
    environment:
      POSTGRES_PASSWORD: test_admin
      POSTGRES_USER: nuvix_admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - nuvix-test
    ports:
      - "${TEST_DB_PORT:-54321}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "PGPASSWORD=test_admin pg_isready -U nuvix_admin -d postgres -h localhost"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: nuvix-test-redis
    depends_on:
      - postgres
    env_file:
      - .env.test
    networks:
      - nuvix-test
    ports:
      - "${TEST_REDIS_PORT:-63791}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nuvix-test:
    driver: bridge
